[package]
name = "breezybot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.89"
poise = "0.6.1"
tokio = "1.40.0"
poem = "3.1.1"
sea-orm = { version = "1.0.1", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-native-tls"] }
futures = "0.3.30"
serde = "1.0.210"
comfy-table = "7.1.1"
serde_json = "1.0.128"
chrono = "0.4.38"
rust-i18n = "3.1.2"
shuttle-runtime = "0.48.0"
shuttle-poise = "0.37.0"
shuttle-secrets = "0.42.0"
shuttle-poem = "0.48.0"
fluent = "0.16.1"
intl-memoizer = "0.5.2"
tracing = "0.1.40"
paste = "1.0.15"
