//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "elections")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Decimal(Some((20, 0)))")]
    pub role: Decimal,
    #[sea_orm(column_type = "Decimal(Some((20, 0)))")]
    pub guild: Decimal,
    pub limit: i16,
    pub scheduled_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub schedule: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::candidates::Entity")]
    Candidates,
}

impl Related<super::candidates::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Candidates.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
