//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guilds")]
pub struct Model {
    #[sea_orm(primary_key, column_type = "Decimal(Some((20, 0)))")]
    pub id: Decimal,
    #[sea_orm(column_type = "Text")]
    pub locale: String,
    #[sea_orm(nullable, column_type = "Decimal(Some((20, 0)))")]
    pub elections_channel: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
