//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

pub use super::candidates::Entity as Candidates;
pub use super::elections::Entity as Elections;
pub use super::guilds::Entity as Guilds;
pub use super::members::Entity as Members;
pub use super::test::Entity as Test;
pub use super::votes::Entity as Votes;
